import { KeyringPair } from "@polkadot/keyring/types";

import { RolesPallet } from "./roles";

/**
 * The class to allow users to perform tx on different pallets (roles, jobs, etc.) on Tangle Network
 */
class Account extends RolesPallet {
  /**
   * @param keyRingPair The keyring pair to sign transactions (must be generated by the users
   * using polkadot-js)
   */
  constructor(keyRingPair: KeyringPair) {
    super(keyRingPair);
  }
}

export default Account;
